# Generated by Django 3.1 on 2020-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_announcement_course_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
