# Generated by Django 3.1 on 2020-09-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Syllabus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
