# Generated by Django 3.1 on 2020-09-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200926_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='forwhich',
            field=models.ForeignKey(default='',blank=True, null=True,on_delete=django.db.models.deletion.CASCADE, related_name='material', to='auctions.course'),
            preserve_default=False,
        ),
    ]
