# Generated by Django 3.1 on 2020-10-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_quries'),
    ]

    operations = [
        migrations.AddField(
            model_name='quries',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
